# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\admin\Desktop\EID_final\access.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(930, 630)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconss/header.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#pushmenuin{\n"
"background-color: rgb(255, 255, 255,40);\n"
"}\n"
"\n"
"#pushmenuin:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 931, 91))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setStyleSheet("*{background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);}\n"
"#pushmenuin{\n"
"background-color: rgb(170, 0, 0);\n"
"    font: 87 10pt \"Arial Black\";\n"
"}\n"
"\n"
"#pushmenuin:hover{\n"
"background-color: rgb(255, 85, 0);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(230, 10, 501, 51))
        self.label_4.setStyleSheet("font: 87 18pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.pushLogout = QtWidgets.QPushButton(self.frame)
        self.pushLogout.setGeometry(QtCore.QRect(830, 30, 61, 41))
        self.pushLogout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushLogout.setStyleSheet("image:url(:/iconss/logout_icon.png)\n"
"")
        self.pushLogout.setText("")
        self.pushLogout.setObjectName("pushLogout")
        self.label_30 = QtWidgets.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(840, 70, 41, 16))
        self.label_30.setObjectName("label_30")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(0, 50, 191, 41))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.pushmenuin = QtWidgets.QCommandLinkButton(self.frame_5)
        self.pushmenuin.setGeometry(QtCore.QRect(0, 0, 191, 41))
        self.pushmenuin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/hamburgericon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/hamburgericon.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/hamburgericon.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/hamburgericon.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/hamburgericon.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.pushmenuin.setIcon(icon1)
        self.pushmenuin.setIconSize(QtCore.QSize(40, 40))
        self.pushmenuin.setObjectName("pushmenuin")
        self.label_4.raise_()
        self.label_30.raise_()
        self.pushLogout.raise_()
        self.frame_5.raise_()
        self.frameList = QtWidgets.QFrame(self.centralwidget)
        self.frameList.setGeometry(QtCore.QRect(0, 90, 931, 481))
        self.frameList.setAutoFillBackground(False)
        self.frameList.setStyleSheet("*{background-color: rgb(250,250,250);\n"
"}\n"
"\n"
"#textData{background-color: rgba(200, 200, 200, 215);}\n"
"#textData:hover{\n"
"background-color: rgba(255, 255, 255, 240);\n"
"}\n"
"#listE{\n"
"background-color: rgb(0, 0, 0,180);\n"
"\n"
"color:white;\n"
"}\n"
"\n"
"#listE:hover{\n"
"background-color: rgb(40, 40, 40);\n"
"color:white;\n"
"}\n"
"\n"
"#pushPrint{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius:5px;\n"
"border-bottom:3px solid rgb(104, 0, 0);\n"
"border-right:3px solid  rgb(104, 0, 0);\n"
"transition: all 1s;\n"
"color:white;\n"
"}\n"
"#pushPrint:hover{\n"
"background-color: rgb(255, 85, 0);\n"
"border-bottom:3px solid rgb(255, 85, 0);\n"
"border-right:3px solid rgb(130, 43, 0);\n"
"}\n"
"\n"
"\n"
"#pushModify{\n"
"background-color: rgb(44, 44, 44);\n"
"border-radius:5px;\n"
"border-bottom:2px solid rgb(0, 0, 0);\n"
"border-right:2px solid  rgb(0, 0, 0);\n"
"transition: all 1s;\n"
"color:white;\n"
"}\n"
"#pushModify:hover{\n"
"background-color: rgb(0, 0, 0);\n"
"border-bottom:2px solid gray;\n"
"border-right:2px solid gray;\n"
"}\n"
"#lineSearch{\n"
"background:transparent;\n"
"border-bottom:1px solid  rgb(0,0,0,170);\n"
"border-left:1px solid  rgb(0,0,0,170);\n"
"border-top:1px solid  rgb(0,0,0,170);\n"
"border-right:1px solid  rgb(0,0,0,170);\n"
"border-radius:5px;\n"
"font: 9pt \"Century Gothic\";\n"
"\n"
"}\n"
"\n"
"#pushPrint_2{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius:5px;\n"
"border-bottom:3px solid rgb(104, 0, 0);\n"
"border-right:3px solid  rgb(104, 0, 0);\n"
"transition: all 1s;\n"
"color:white;\n"
"}\n"
"#pushPrint_2:hover{\n"
"background-color: rgb(255, 85, 0);\n"
"border-bottom:3px solid rgb(255, 85, 0);\n"
"border-right:3px solid rgb(130, 43, 0);\n"
"}\n"
"#pic{\n"
"border-bottom:1px solid  rgb(0,0,0,170);\n"
"border-left:1px solid  rgb(0,0,0,170);\n"
"border-top:1px solid  rgb(0,0,0,170);\n"
"border-right:1px solid  rgb(0,0,0,170);\n"
"}\n"
"")
        self.frameList.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameList.setObjectName("frameList")
        self.pushPrint = QtWidgets.QPushButton(self.frameList)
        self.pushPrint.setGeometry(QtCore.QRect(690, 440, 75, 23))
        self.pushPrint.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushPrint.setStyleSheet("")
        self.pushPrint.setObjectName("pushPrint")
        self.lineSearch = QtWidgets.QLineEdit(self.frameList)
        self.lineSearch.setGeometry(QtCore.QRect(220, 10, 591, 21))
        self.lineSearch.setObjectName("lineSearch")
        self.textData = QtWidgets.QTextEdit(self.frameList)
        self.textData.setGeometry(QtCore.QRect(490, 220, 311, 211))
        self.textData.setStyleSheet("")
        self.textData.setObjectName("textData")
        self.pushModify = QtWidgets.QPushButton(self.frameList)
        self.pushModify.setGeometry(QtCore.QRect(550, 440, 75, 23))
        self.pushModify.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushModify.setStyleSheet("")
        self.pushModify.setObjectName("pushModify")
        self.comboList = QtWidgets.QComboBox(self.frameList)
        self.comboList.setGeometry(QtCore.QRect(250, 50, 151, 22))
        self.comboList.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboList.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 44, 44);")
        self.comboList.setObjectName("comboList")
        self.comboList.addItem("")
        self.comboList.addItem("")
        self.comboList.addItem("")
        self.comboList.addItem("")
        self.comboList.addItem("")
        self.comboList.addItem("")
        self.listE = QtWidgets.QListWidget(self.frameList)
        self.listE.setGeometry(QtCore.QRect(150, 100, 291, 331))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.listE.setPalette(palette)
        self.listE.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listE.setStyleSheet("font: 10pt \"Impact\";")
        self.listE.setObjectName("listE")
        item = QtWidgets.QListWidgetItem()
        self.listE.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listE.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listE.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listE.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listE.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listE.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listE.addItem(item)
        self.label_31 = QtWidgets.QLabel(self.frameList)
        self.label_31.setGeometry(QtCore.QRect(110, 50, 141, 20))
        self.label_31.setStyleSheet("font: 10pt \"Arial Black\";")
        self.label_31.setObjectName("label_31")
        self.pushPrint_2 = QtWidgets.QPushButton(self.frameList)
        self.pushPrint_2.setGeometry(QtCore.QRect(220, 440, 151, 31))
        self.pushPrint_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushPrint_2.setStyleSheet("")
        self.pushPrint_2.setObjectName("pushPrint_2")
        self.pic = QtWidgets.QLabel(self.frameList)
        self.pic.setGeometry(QtCore.QRect(570, 60, 171, 151))
        self.pic.setText("")
        self.pic.setScaledContents(True)
        self.pic.setObjectName("pic")
        self.label_33 = QtWidgets.QLabel(self.frameList)
        self.label_33.setGeometry(QtCore.QRect(110, 10, 101, 20))
        self.label_33.setStyleSheet("font: 10pt \"Arial Black\";")
        self.label_33.setObjectName("label_33")
        self.label_11 = QtWidgets.QLabel(self.frameList)
        self.label_11.setGeometry(QtCore.QRect(410, 50, 471, 391))
        self.label_11.setStyleSheet("image: url(:/iconss/header.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frameList)
        self.label_12.setGeometry(QtCore.QRect(160, 80, 201, 16))
        self.label_12.setObjectName("label_12")
        self.label_11.raise_()
        self.label_33.raise_()
        self.pushPrint.raise_()
        self.lineSearch.raise_()
        self.textData.raise_()
        self.pushModify.raise_()
        self.comboList.raise_()
        self.listE.raise_()
        self.label_31.raise_()
        self.pushPrint_2.raise_()
        self.pic.raise_()
        self.label_12.raise_()
        self.frameleave = QtWidgets.QFrame(self.centralwidget)
        self.frameleave.setGeometry(QtCore.QRect(1270, 10, 251, 221))
        self.frameleave.setStyleSheet("*{\n"
"background-color:rgb(250,250,250);\n"
"}\n"
"#pushmenuin2{\n"
"background-color: rgb(255, 255, 255,40);\n"
"}\n"
"\n"
"#pushmenuin2:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.frameleave.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameleave.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameleave.setObjectName("frameleave")
        self.frameACC = QtWidgets.QFrame(self.centralwidget)
        self.frameACC.setGeometry(QtCore.QRect(1290, 260, 261, 181))
        self.frameACC.setStyleSheet("*{\n"
"background-color:rgb(250,250,250);\n"
"}\n"
"#pushmenuin3{\n"
"background-color: rgb(255, 255, 255,40);\n"
"}\n"
"\n"
"#pushmenuin3:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.frameACC.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameACC.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameACC.setObjectName("frameACC")
        self.frame_2 = QtWidgets.QFrame(self.frameACC)
        self.frame_2.setGeometry(QtCore.QRect(200, 90, 511, 301))
        self.frame_2.setStyleSheet("*{background-color: rgb(0, 0, 0,160);\n"
"border-radius:12px;\n"
"\n"
"}\n"
"#label_74{\n"
"background:transparent;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background:transparent;\n"
"border-bottom:2px solid  white;\n"
"border-radius:5px;\n"
"font-family:century gothic;\n"
"color:white;\n"
"}\n"
"QLineEdit:hover{\n"
"background-color: rgb(48, 48, 48);\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(44, 44, 44);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"border-radius:15px;\n"
"display: inline-block;\n"
"text-decoration: none;\n"
"border-bottom:3px solid  rgb(0,0,0);\n"
"border-right:3px solid  rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 0,230);\n"
"\n"
"}\n"
"#lineEdit_8{\n"
"font-size:12.5pt;\n"
"\n"
"}\n"
"#lineEdit_9{\n"
"font-size:12.5pt;\n"
"\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_74 = QtWidgets.QLabel(self.frame_2)
        self.label_74.setGeometry(QtCore.QRect(40, 20, 131, 91))
        self.label_74.setStyleSheet("image: url(:/iconss/account_settings.png);")
        self.label_74.setText("")
        self.label_74.setObjectName("label_74")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 242, 211, 31))
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 200, 211, 31))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(0, 160, 211, 31))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 120, 211, 31))
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setObjectName("pushButton_10")
        self.frameinfo = QtWidgets.QFrame(self.frame_2)
        self.frameinfo.setGeometry(QtCore.QRect(220, 10, 241, 271))
        self.frameinfo.setStyleSheet("QLabel{\n"
"background:transparent;\n"
"color: white;\n"
"font-family:century-gothic;\n"
"}")
        self.frameinfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameinfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameinfo.setObjectName("frameinfo")
        self.label_78 = QtWidgets.QLabel(self.frameinfo)
        self.label_78.setGeometry(QtCore.QRect(20, 30, 81, 21))
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.frameinfo)
        self.label_79.setGeometry(QtCore.QRect(10, 80, 121, 21))
        self.label_79.setStyleSheet("")
        self.label_79.setObjectName("label_79")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frameinfo)
        self.lineEdit_8.setGeometry(QtCore.QRect(12, 50, 221, 20))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frameinfo)
        self.lineEdit_9.setGeometry(QtCore.QRect(10, 110, 221, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.frameuser = QtWidgets.QFrame(self.frame_2)
        self.frameuser.setGeometry(QtCore.QRect(220, 10, 241, 271))
        self.frameuser.setStyleSheet("QLabel{\n"
"background:transparent;\n"
"color: white;\n"
"font-family:century-gothic;\n"
"}\n"
"#confirmuser{\n"
"background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"border-radius:15px;\n"
"border-bottom:3px solid rgb(104, 0, 0);\n"
"border-right:3px solid  rgb(104, 0, 0);\n"
"transition: all 1s;\n"
"}\n"
"#confirmuser:hover{\n"
"background-color: rgb(255, 85, 0);\n"
"border-bottom:3px solid  rgb(130, 43, 0);\n"
"border-right:3px solid rgb(130, 43, 0);\n"
"}\n"
"\n"
"")
        self.frameuser.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameuser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameuser.setObjectName("frameuser")
        self.label_81 = QtWidgets.QLabel(self.frameuser)
        self.label_81.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.frameuser)
        self.label_82.setGeometry(QtCore.QRect(10, 80, 121, 21))
        self.label_82.setStyleSheet("")
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(self.frameuser)
        self.label_83.setGeometry(QtCore.QRect(10, 140, 91, 21))
        self.label_83.setObjectName("label_83")
        self.confirmuser = QtWidgets.QPushButton(self.frameuser)
        self.confirmuser.setGeometry(QtCore.QRect(80, 210, 75, 23))
        self.confirmuser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirmuser.setObjectName("confirmuser")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frameuser)
        self.lineEdit_11.setGeometry(QtCore.QRect(12, 50, 221, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frameuser)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 110, 221, 20))
        self.lineEdit_12.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frameuser)
        self.lineEdit_13.setGeometry(QtCore.QRect(10, 170, 221, 20))
        self.lineEdit_13.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.framepass = QtWidgets.QFrame(self.frame_2)
        self.framepass.setGeometry(QtCore.QRect(220, 10, 241, 271))
        self.framepass.setStyleSheet("QLabel{\n"
"background:transparent;\n"
"color: white;\n"
"font-family:century-gothic;\n"
"}\n"
"#confirmpass{\n"
"background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"border-radius:15px;\n"
"border-bottom:3px solid rgb(104, 0, 0);\n"
"border-right:3px solid  rgb(104, 0, 0);\n"
"transition: all 1s;\n"
"}\n"
"#confirmpass:hover{\n"
"background-color: rgb(255, 85, 0);\n"
"border-bottom:3px solid  rgb(130, 43, 0);\n"
"border-right:3px solid rgb(130, 43, 0);\n"
"}\n"
"")
        self.framepass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framepass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framepass.setObjectName("framepass")
        self.label_84 = QtWidgets.QLabel(self.framepass)
        self.label_84.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.framepass)
        self.label_85.setGeometry(QtCore.QRect(10, 80, 121, 21))
        self.label_85.setStyleSheet("")
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.framepass)
        self.label_86.setGeometry(QtCore.QRect(10, 140, 91, 21))
        self.label_86.setObjectName("label_86")
        self.confirmpass = QtWidgets.QPushButton(self.framepass)
        self.confirmpass.setGeometry(QtCore.QRect(80, 210, 75, 23))
        self.confirmpass.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirmpass.setObjectName("confirmpass")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.framepass)
        self.lineEdit_14.setGeometry(QtCore.QRect(12, 50, 221, 20))
        self.lineEdit_14.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.framepass)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 110, 221, 20))
        self.lineEdit_15.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.framepass)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 170, 221, 20))
        self.lineEdit_16.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.framepass_2 = QtWidgets.QFrame(self.frame_2)
        self.framepass_2.setGeometry(QtCore.QRect(220, 10, 241, 271))
        self.framepass_2.setStyleSheet("QLabel{\n"
"background:transparent;\n"
"color: white;\n"
"font-family:century-gothic;\n"
"}\n"
"#confirmpass_3{\n"
"background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"border-radius:15px;\n"
"border-bottom:3px solid rgb(104, 0, 0);\n"
"border-right:3px solid  rgb(104, 0, 0);\n"
"transition: all 1s;\n"
"}\n"
"#confirmpass_3:hover{\n"
"background-color: rgb(255, 85, 0);\n"
"border-bottom:3px solid  rgb(130, 43, 0);\n"
"border-right:3px solid rgb(130, 43, 0);\n"
"}\n"
"")
        self.framepass_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framepass_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framepass_2.setObjectName("framepass_2")
        self.label_90 = QtWidgets.QLabel(self.framepass_2)
        self.label_90.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.framepass_2)
        self.label_91.setGeometry(QtCore.QRect(10, 80, 121, 21))
        self.label_91.setStyleSheet("")
        self.label_91.setObjectName("label_91")
        self.label_92 = QtWidgets.QLabel(self.framepass_2)
        self.label_92.setGeometry(QtCore.QRect(10, 140, 141, 21))
        self.label_92.setObjectName("label_92")
        self.confirmpass_3 = QtWidgets.QPushButton(self.framepass_2)
        self.confirmpass_3.setGeometry(QtCore.QRect(80, 210, 75, 23))
        self.confirmpass_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirmpass_3.setObjectName("confirmpass_3")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.framepass_2)
        self.lineEdit_20.setGeometry(QtCore.QRect(12, 50, 221, 20))
        self.lineEdit_20.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.framepass_2)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 110, 221, 20))
        self.lineEdit_21.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.framepass_2)
        self.lineEdit_22.setGeometry(QtCore.QRect(10, 170, 221, 20))
        self.lineEdit_22.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_74.raise_()
        self.pushButton_9.raise_()
        self.pushButton_8.raise_()
        self.pushButton.raise_()
        self.pushButton_10.raise_()
        self.framepass_2.raise_()
        self.frameinfo.raise_()
        self.framepass.raise_()
        self.frameuser.raise_()
        self.label_75 = QtWidgets.QLabel(self.frameACC)
        self.label_75.setGeometry(QtCore.QRect(60, 20, 201, 31))
        self.label_75.setStyleSheet("font: 15pt \"Arial Black\";")
        self.label_75.setObjectName("label_75")
        self.framenotif = QtWidgets.QFrame(self.centralwidget)
        self.framenotif.setGeometry(QtCore.QRect(940, 30, 81, 51))
        self.framenotif.setStyleSheet("#framenotif{\n"
"background-color:rgb(250,250,250);\n"
"}\n"
"\n"
"#pushupdatenotif{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius:5px;\n"
"border-bottom:3px solid rgb(104, 0, 0);\n"
"border-right:3px solid  rgb(104, 0, 0);\n"
"transition: all 1s;\n"
"color:white;\n"
"}\n"
"#pushupdatenotif:hover{\n"
"background-color: rgb(255, 85, 0);\n"
"border-bottom:3px solid rgb(130, 43, 0);\n"
"border-right:3px solid rgb(130, 43, 0);\n"
"}")
        self.framenotif.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.framenotif.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.framenotif.setObjectName("framenotif")
        self.label_32 = QtWidgets.QLabel(self.framenotif)
        self.label_32.setGeometry(QtCore.QRect(20, 10, 181, 20))
        self.label_32.setStyleSheet("font: 13pt \"Arial Black\";")
        self.label_32.setObjectName("label_32")
        self.pushupdatenotif = QtWidgets.QPushButton(self.framenotif)
        self.pushupdatenotif.setGeometry(QtCore.QRect(610, 420, 101, 21))
        self.pushupdatenotif.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushupdatenotif.setStyleSheet("")
        self.pushupdatenotif.setObjectName("pushupdatenotif")
        self.listnotif = QtWidgets.QListWidget(self.framenotif)
        self.listnotif.setGeometry(QtCore.QRect(20, 50, 401, 391))
        self.listnotif.setStyleSheet("font: 10pt \"Arial Black\";")
        self.listnotif.setObjectName("listnotif")
        self.label_13 = QtWidgets.QLabel(self.framenotif)
        self.label_13.setGeometry(QtCore.QRect(400, 40, 471, 391))
        self.label_13.setStyleSheet("image: url(:/iconss/header.png);\n"
"opacity:0.5;")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.textviewnotif = QtWidgets.QTextEdit(self.framenotif)
        self.textviewnotif.setGeometry(QtCore.QRect(440, 70, 451, 341))
        self.textviewnotif.setStyleSheet("background-color: rgba(200, 200, 200,115);\n"
"")
        self.textviewnotif.setReadOnly(True)
        self.textviewnotif.setObjectName("textviewnotif")
        self.frame_3 = QtWidgets.QFrame(self.framenotif)
        self.frame_3.setGeometry(QtCore.QRect(420, 30, 431, 391))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255,110);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_7 = QtWidgets.QLabel(self.framenotif)
        self.label_7.setGeometry(QtCore.QRect(30, 30, 191, 16))
        self.label_7.setObjectName("label_7")
        self.label_13.raise_()
        self.frame_3.raise_()
        self.label_32.raise_()
        self.pushupdatenotif.raise_()
        self.listnotif.raise_()
        self.textviewnotif.raise_()
        self.label_7.raise_()
        self.footer = QtWidgets.QFrame(self.centralwidget)
        self.footer.setGeometry(QtCore.QRect(0, 570, 931, 61))
        self.footer.setStyleSheet("background-color: rgb(163, 163, 163);")
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName("footer")
        self.label_3 = QtWidgets.QLabel(self.footer)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.footer)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.footer)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.footer)
        self.label_10.setGeometry(QtCore.QRect(300, 40, 251, 16))
        self.label_10.setObjectName("label_10")
        self.menu = QtWidgets.QFrame(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(-190, 90, 191, 541))
        self.menu.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.menu.setStyleSheet("*{background-color: rgb(0, 0, 0,240);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(44, 44, 44);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"border-radius:3px;\n"
"display: inline-block;\n"
"padding: 0.5em 1em;\n"
"text-decoration: none;\n"
"border-bottom:3px solid  rgb(0,0,0);\n"
"border-right:3px solid  rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"background:black;\n"
"\n"
"}\n"
"#label_31{\n"
"background:transparent;\n"
"    font: 16pt \"Impact\";\n"
"}\n"
"QLabel{\n"
"background:transparent;\n"
"}")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.commandLinkButton_4 = QtWidgets.QPushButton(self.menu)
        self.commandLinkButton_4.setGeometry(QtCore.QRect(0, 60, 191, 61))
        self.commandLinkButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton_4.setStyleSheet("")
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.commandLinkButton = QtWidgets.QPushButton(self.menu)
        self.commandLinkButton.setGeometry(QtCore.QRect(0, 140, 191, 61))
        self.commandLinkButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commandLinkButton.setStyleSheet("")
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.pushACC = QtWidgets.QPushButton(self.menu)
        self.pushACC.setGeometry(QtCore.QRect(0, 220, 191, 61))
        self.pushACC.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushACC.setStyleSheet("")
        self.pushACC.setObjectName("pushACC")
        self.pushACC_2 = QtWidgets.QPushButton(self.menu)
        self.pushACC_2.setGeometry(QtCore.QRect(0, 300, 191, 61))
        self.pushACC_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushACC_2.setStyleSheet("")
        self.pushACC_2.setObjectName("pushACC_2")
        self.pushmenuout = QtWidgets.QPushButton(self.menu)
        self.pushmenuout.setGeometry(QtCore.QRect(150, 0, 51, 41))
        self.pushmenuout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushmenuout.setStyleSheet("background-color: transparent;\n"
"border-radius:20px;\n"
"image: url(:/newPrefix/closemenu.png);")
        self.pushmenuout.setText("")
        self.pushmenuout.setIconSize(QtCore.QSize(14, 14))
        self.pushmenuout.setObjectName("pushmenuout")
        self.frameAdd_2 = QtWidgets.QFrame(self.centralwidget)
        self.frameAdd_2.setGeometry(QtCore.QRect(930, 140, 101, 171))
        self.frameAdd_2.setStyleSheet("*{background-color: rgb(250,250,250);\n"
"font: 10pt \"Impact\";\n"
"color:black;\n"
"\n"
"}\n"
"#frame_4{\n"
"\n"
"background-color: rgb(0, 0, 0,32);\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"QLabel{\n"
"background:transparent;\n"
"}\n"
"#frame_8{\n"
"background:transparent;\n"
"border:1px solid black;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"#groupBox_7{\n"
"background:transparent;\n"
"border:1px solid black;\n"
"border-radius:8px\n"
"}\n"
"QLineEdit{\n"
"background:transparent;\n"
"border-bottom:2px solid  rgb(0,0,0,170);\n"
"border-radius:5px;\n"
"font-size:9pt;\n"
"font-family:century gothic;\n"
"}\n"
"QLineEdit:hover{\n"
"background-color: rgb(186, 186, 186);\n"
"}\n"
"#comboBox_3{\n"
"font-family:century gothic;\n"
"}\n"
"#pushmenuin1{\n"
"background-color: rgb(255, 255, 255,40);\n"
"}\n"
"\n"
"#pushmenuin1:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"#pushbrowsepic{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius:5px;\n"
"border-bottom:3px solid rgb(104, 0, 0);\n"
"border-right:3px solid  rgb(104, 0, 0);\n"
"transition: all 1s;\n"
"color:white;\n"
"}\n"
"#pushbrowsepic:hover{\n"
"background-color: rgb(255, 85, 0);\n"
"border-bottom:3px solid rgb(130, 43, 0);\n"
"border-right:3px solid rgb(130, 43, 0);\n"
"}\n"
"#pushtakephoto{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius:5px;\n"
"border-bottom:3px solid rgb(104, 0, 0);\n"
"border-right:3px solid  rgb(104, 0, 0);\n"
"transition: all 1s;\n"
"color:white;\n"
"}\n"
"#pushtakephoto:hover{\n"
"background-color: rgb(255, 85, 0);\n"
"border-bottom:3px solid rgb(130, 43, 0);\n"
"border-right:3px solid rgb(130, 43, 0);\n"
"}\n"
"#pushAdd{\n"
"background-color: rgb(170, 0, 0);\n"
"border-radius:5px;\n"
"border-bottom:3px solid rgb(104, 0, 0);\n"
"border-right:3px solid  rgb(104, 0, 0);\n"
"transition: all 1s;\n"
"color:white;\n"
"}\n"
"#pushAdd:hover{\n"
"background-color: rgb(255, 85, 0);\n"
"border-bottom:3px solid rgb(130, 43, 0);\n"
"border-right:3px solid rgb(130, 43, 0);\n"
"}\n"
"#textEdit{\n"
"border:1px solid black;\n"
"border-radius:8px;\n"
"font-size:9pt;\n"
"font-family:century gothic;\n"
"\n"
"}\n"
"#label_2{\n"
"font-size:8pt;\n"
"font-family:century gothic,bold;\n"
"\n"
"}")
        self.frameAdd_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameAdd_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameAdd_2.setObjectName("frameAdd_2")
        self.frame_4 = QtWidgets.QFrame(self.frameAdd_2)
        self.frame_4.setGeometry(QtCore.QRect(30, 10, 841, 451))
        self.frame_4.setStyleSheet("#frame_4{\n"
"\n"
"background-color: rgb(0, 0, 0,32);\n"
"color:white;\n"
"border-radius:20px;\n"
"}")
        self.frame_4.setObjectName("frame_4")
        self.label_53 = QtWidgets.QLabel(self.frame_4)
        self.label_53.setGeometry(QtCore.QRect(31, 51, 80, 17))
        self.label_53.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.frame_4)
        self.label_54.setGeometry(QtCore.QRect(31, 78, 87, 17))
        self.label_54.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.frame_4)
        self.label_55.setGeometry(QtCore.QRect(31, 105, 79, 17))
        self.label_55.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_55.setObjectName("label_55")
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_7.setGeometry(QtCore.QRect(40, 190, 181, 51))
        self.groupBox_7.setStyleSheet("font: 10pt \"Impact\";")
        self.groupBox_7.setObjectName("groupBox_7")
        self.radioMale_3 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioMale_3.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioMale_3.setObjectName("radioMale_3")
        self.radioFemale_3 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioFemale_3.setGeometry(QtCore.QRect(70, 20, 61, 17))
        self.radioFemale_3.setObjectName("radioFemale_3")
        self.label_57 = QtWidgets.QLabel(self.frame_4)
        self.label_57.setGeometry(QtCore.QRect(21, 241, 88, 17))
        self.label_57.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.frame_4)
        self.label_58.setGeometry(QtCore.QRect(21, 270, 96, 17))
        self.label_58.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.frame_4)
        self.label_59.setGeometry(QtCore.QRect(21, 299, 112, 17))
        self.label_59.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.frame_4)
        self.label_60.setGeometry(QtCore.QRect(331, 41, 162, 17))
        self.label_60.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.frame_4)
        self.label_61.setGeometry(QtCore.QRect(21, 328, 138, 17))
        self.label_61.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_61.setObjectName("label_61")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_3.setGeometry(QtCore.QRect(139, 351, 171, 18))
        self.comboBox_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(44, 44, 44);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.lineFirstname_3 = QtWidgets.QLineEdit(self.frame_4)
        self.lineFirstname_3.setGeometry(QtCore.QRect(124, 51, 191, 21))
        self.lineFirstname_3.setMaxLength(60)
        self.lineFirstname_3.setObjectName("lineFirstname_3")
        self.lineMid_3 = QtWidgets.QLineEdit(self.frame_4)
        self.lineMid_3.setGeometry(QtCore.QRect(124, 78, 191, 21))
        self.lineMid_3.setMaxLength(30)
        self.lineMid_3.setObjectName("lineMid_3")
        self.lineLastname_3 = QtWidgets.QLineEdit(self.frame_4)
        self.lineLastname_3.setGeometry(QtCore.QRect(124, 105, 191, 21))
        self.lineLastname_3.setMaxLength(30)
        self.lineLastname_3.setObjectName("lineLastname_3")
        self.lineDesignation_3 = QtWidgets.QLineEdit(self.frame_4)
        self.lineDesignation_3.setGeometry(QtCore.QRect(139, 241, 171, 17))
        self.lineDesignation_3.setMaxLength(50)
        self.lineDesignation_3.setObjectName("lineDesignation_3")
        self.lineSalaryg_3 = QtWidgets.QLineEdit(self.frame_4)
        self.lineSalaryg_3.setGeometry(QtCore.QRect(139, 270, 171, 17))
        self.lineSalaryg_3.setMaxLength(10)
        self.lineSalaryg_3.setObjectName("lineSalaryg_3")
        self.lineStepincre_3 = QtWidgets.QLineEdit(self.frame_4)
        self.lineStepincre_3.setGeometry(QtCore.QRect(139, 299, 171, 17))
        self.lineStepincre_3.setMaxLength(10)
        self.lineStepincre_3.setObjectName("lineStepincre_3")
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setGeometry(QtCore.QRect(380, 200, 351, 191))
        self.frame_8.setStyleSheet("")
        self.frame_8.setObjectName("frame_8")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout.setObjectName("gridLayout")
        self.label_66 = QtWidgets.QLabel(self.frame_8)
        self.label_66.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_66.setObjectName("label_66")
        self.gridLayout.addWidget(self.label_66, 5, 0, 1, 1)
        self.lineTin_3 = QtWidgets.QLineEdit(self.frame_8)
        self.lineTin_3.setMaxLength(9)
        self.lineTin_3.setObjectName("lineTin_3")
        self.gridLayout.addWidget(self.lineTin_3, 1, 1, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.frame_8)
        self.label_63.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_63.setObjectName("label_63")
        self.gridLayout.addWidget(self.label_63, 2, 0, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.frame_8)
        self.label_65.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_65.setObjectName("label_65")
        self.gridLayout.addWidget(self.label_65, 4, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.frame_8)
        self.label_64.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_64.setObjectName("label_64")
        self.gridLayout.addWidget(self.label_64, 3, 0, 1, 1)
        self.linePhil_3 = QtWidgets.QLineEdit(self.frame_8)
        self.linePhil_3.setText("")
        self.linePhil_3.setMaxLength(12)
        self.linePhil_3.setObjectName("linePhil_3")
        self.gridLayout.addWidget(self.linePhil_3, 5, 1, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.frame_8)
        self.label_67.setStyleSheet("font: 11pt \"Arial Black\";")
        self.label_67.setObjectName("label_67")
        self.gridLayout.addWidget(self.label_67, 0, 0, 1, 2)
        self.label_62 = QtWidgets.QLabel(self.frame_8)
        self.label_62.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_62.setObjectName("label_62")
        self.gridLayout.addWidget(self.label_62, 1, 0, 1, 1)
        self.linePagibig_3 = QtWidgets.QLineEdit(self.frame_8)
        self.linePagibig_3.setText("")
        self.linePagibig_3.setMaxLength(12)
        self.linePagibig_3.setObjectName("linePagibig_3")
        self.gridLayout.addWidget(self.linePagibig_3, 4, 1, 1, 1)
        self.lineSss_3 = QtWidgets.QLineEdit(self.frame_8)
        self.lineSss_3.setText("")
        self.lineSss_3.setMaxLength(10)
        self.lineSss_3.setObjectName("lineSss_3")
        self.gridLayout.addWidget(self.lineSss_3, 3, 1, 1, 1)
        self.lineGsis_3 = QtWidgets.QLineEdit(self.frame_8)
        self.lineGsis_3.setText("")
        self.lineGsis_3.setMaxLength(11)
        self.lineGsis_3.setObjectName("lineGsis_3")
        self.gridLayout.addWidget(self.lineGsis_3, 2, 1, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.frame_4)
        self.label_68.setGeometry(QtCore.QRect(331, 149, 48, 17))
        self.label_68.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_68.setObjectName("label_68")
        self.lineEmail_3 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEmail_3.setGeometry(QtCore.QRect(499, 149, 171, 21))
        self.lineEmail_3.setMaxLength(200)
        self.lineEmail_3.setObjectName("lineEmail_3")
        self.label_69 = QtWidgets.QLabel(self.frame_4)
        self.label_69.setGeometry(QtCore.QRect(331, 122, 107, 17))
        self.label_69.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_69.setObjectName("label_69")
        self.linePhone_7 = QtWidgets.QLineEdit(self.frame_4)
        self.linePhone_7.setGeometry(QtCore.QRect(499, 122, 171, 21))
        self.linePhone_7.setMaxLength(11)
        self.linePhone_7.setObjectName("linePhone_7")
        self.pushAdd = QtWidgets.QPushButton(self.frame_4)
        self.pushAdd.setGeometry(QtCore.QRect(500, 400, 111, 21))
        self.pushAdd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushAdd.setStyleSheet("")
        self.pushAdd.setObjectName("pushAdd")
        self.label_70 = QtWidgets.QLabel(self.frame_4)
        self.label_70.setGeometry(QtCore.QRect(20, 10, 291, 16))
        self.label_70.setStyleSheet("font: 11pt \"Arial Black\";")
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.frame_4)
        self.label_71.setGeometry(QtCore.QRect(331, 95, 49, 17))
        self.label_71.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_71.setObjectName("label_71")
        self.linePhone_8 = QtWidgets.QLineEdit(self.frame_4)
        self.linePhone_8.setGeometry(QtCore.QRect(499, 95, 171, 21))
        self.linePhone_8.setMaxLength(10)
        self.linePhone_8.setObjectName("linePhone_8")
        self.linePhone_9 = QtWidgets.QLineEdit(self.frame_4)
        self.linePhone_9.setGeometry(QtCore.QRect(124, 132, 191, 21))
        self.linePhone_9.setMaxLength(10)
        self.linePhone_9.setObjectName("linePhone_9")
        self.label_72 = QtWidgets.QLabel(self.frame_4)
        self.label_72.setGeometry(QtCore.QRect(31, 132, 65, 17))
        self.label_72.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_72.setObjectName("label_72")
        self.dateEdit = QtWidgets.QDateEdit(self.frame_4)
        self.dateEdit.setGeometry(QtCore.QRect(499, 41, 171, 21))
        self.dateEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dateEdit.setStyleSheet("font: 10pt \"Century Gothic\";\n"
"font-color: black;")
        self.dateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2099, 1, 1), QtCore.QTime(23, 59, 59)))
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1901, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.pushbrowsepic = QtWidgets.QPushButton(self.frame_4)
        self.pushbrowsepic.setGeometry(QtCore.QRect(710, 110, 111, 23))
        self.pushbrowsepic.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushbrowsepic.setStyleSheet("font: 8pt \"Impact\";")
        self.pushbrowsepic.setObjectName("pushbrowsepic")
        self.label_73 = QtWidgets.QLabel(self.frame_4)
        self.label_73.setGeometry(QtCore.QRect(331, 68, 140, 17))
        self.label_73.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_73.setObjectName("label_73")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.frame_4)
        self.dateEdit_2.setGeometry(QtCore.QRect(499, 68, 171, 21))
        self.dateEdit_2.setStyleSheet("font: 10pt \"Century Gothic\";\n"
"font-color:black;")
        self.dateEdit_2.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2099, 1, 1), QtCore.QTime(23, 59, 59)))
        self.dateEdit_2.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1901, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_77 = QtWidgets.QLabel(self.frame_4)
        self.label_77.setGeometry(QtCore.QRect(20, 400, 61, 20))
        self.label_77.setStyleSheet("font: 10pt \"Impact\";")
        self.label_77.setObjectName("label_77")
        self.textEdit = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit.setGeometry(QtCore.QRect(80, 380, 231, 61))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(350, 10, 371, 16))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.frame_4)
        self.line.setGeometry(QtCore.QRect(320, 0, 1, 461))
        self.line.setStyleSheet("background-color: black;\n"
"")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(710, 10, 111, 101))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.frame_4)
        self.line_2.setGeometry(QtCore.QRect(320, 180, 521, 1))
        self.line_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.dateEdit_3 = QtWidgets.QDateEdit(self.frame_4)
        self.dateEdit_3.setGeometry(QtCore.QRect(124, 159, 161, 21))
        self.dateEdit_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dateEdit_3.setStyleSheet("font: 10pt \"Century Gothic\";\n"
"font-color:black;")
        self.dateEdit_3.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2099, 1, 1), QtCore.QTime(23, 59, 59)))
        self.dateEdit_3.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1901, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_3.setCalendarPopup(True)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.label_56 = QtWidgets.QLabel(self.frame_4)
        self.label_56.setGeometry(QtCore.QRect(31, 159, 66, 17))
        self.label_56.setStyleSheet("font: 9pt \"Arial Black\";")
        self.label_56.setObjectName("label_56")
        self.frameList.raise_()
        self.footer.raise_()
        self.frame.raise_()
        self.frameleave.raise_()
        self.frameACC.raise_()
        self.frameAdd_2.raise_()
        self.framenotif.raise_()
        self.menu.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineFirstname_3, self.lineMid_3)
        MainWindow.setTabOrder(self.lineMid_3, self.lineLastname_3)
        MainWindow.setTabOrder(self.lineLastname_3, self.linePhone_9)
        MainWindow.setTabOrder(self.linePhone_9, self.dateEdit_3)
        MainWindow.setTabOrder(self.dateEdit_3, self.lineDesignation_3)
        MainWindow.setTabOrder(self.lineDesignation_3, self.lineSalaryg_3)
        MainWindow.setTabOrder(self.lineSalaryg_3, self.lineStepincre_3)
        MainWindow.setTabOrder(self.lineStepincre_3, self.dateEdit)
        MainWindow.setTabOrder(self.dateEdit, self.linePhone_8)
        MainWindow.setTabOrder(self.linePhone_8, self.linePhone_7)
        MainWindow.setTabOrder(self.linePhone_7, self.lineEmail_3)
        MainWindow.setTabOrder(self.lineEmail_3, self.lineTin_3)
        MainWindow.setTabOrder(self.lineTin_3, self.lineGsis_3)
        MainWindow.setTabOrder(self.lineGsis_3, self.lineSss_3)
        MainWindow.setTabOrder(self.lineSss_3, self.linePagibig_3)
        MainWindow.setTabOrder(self.linePagibig_3, self.linePhil_3)
        MainWindow.setTabOrder(self.linePhil_3, self.pushAdd)
        MainWindow.setTabOrder(self.pushAdd, self.pushLogout)
        MainWindow.setTabOrder(self.pushLogout, self.listE)
        MainWindow.setTabOrder(self.listE, self.comboBox_3)
        MainWindow.setTabOrder(self.comboBox_3, self.comboList)
        MainWindow.setTabOrder(self.comboList, self.pushPrint)
        MainWindow.setTabOrder(self.pushPrint, self.textData)
        MainWindow.setTabOrder(self.textData, self.radioFemale_3)
        MainWindow.setTabOrder(self.radioFemale_3, self.radioMale_3)
        MainWindow.setTabOrder(self.radioMale_3, self.pushButton_8)
        MainWindow.setTabOrder(self.pushButton_8, self.pushPrint_2)
        MainWindow.setTabOrder(self.pushPrint_2, self.lineSearch)
        MainWindow.setTabOrder(self.lineSearch, self.pushButton_9)
        MainWindow.setTabOrder(self.pushButton_9, self.pushModify)
        MainWindow.setTabOrder(self.pushModify, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_10)
        MainWindow.setTabOrder(self.pushButton_10, self.lineEdit_8)
        MainWindow.setTabOrder(self.lineEdit_8, self.lineEdit_9)
        MainWindow.setTabOrder(self.lineEdit_9, self.confirmuser)
        MainWindow.setTabOrder(self.confirmuser, self.lineEdit_11)
        MainWindow.setTabOrder(self.lineEdit_11, self.lineEdit_12)
        MainWindow.setTabOrder(self.lineEdit_12, self.lineEdit_13)
        MainWindow.setTabOrder(self.lineEdit_13, self.confirmpass)
        MainWindow.setTabOrder(self.confirmpass, self.lineEdit_14)
        MainWindow.setTabOrder(self.lineEdit_14, self.lineEdit_15)
        MainWindow.setTabOrder(self.lineEdit_15, self.lineEdit_16)
        MainWindow.setTabOrder(self.lineEdit_16, self.confirmpass_3)
        MainWindow.setTabOrder(self.confirmpass_3, self.lineEdit_20)
        MainWindow.setTabOrder(self.lineEdit_20, self.lineEdit_21)
        MainWindow.setTabOrder(self.lineEdit_21, self.lineEdit_22)
        MainWindow.setTabOrder(self.lineEdit_22, self.commandLinkButton_4)
        MainWindow.setTabOrder(self.commandLinkButton_4, self.commandLinkButton)
        MainWindow.setTabOrder(self.commandLinkButton, self.pushACC)
        MainWindow.setTabOrder(self.pushACC, self.pushmenuout)
        MainWindow.setTabOrder(self.pushmenuout, self.pushACC_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Welcome to  Employee Information Database"))
        self.label_4.setText(_translate("MainWindow", "EMPLOYEE INFORMATION DATABASE"))
        self.label_30.setText(_translate("MainWindow", "LOGOUT"))
        self.pushmenuin.setText(_translate("MainWindow", "Main Menu"))
        self.pushPrint.setText(_translate("MainWindow", "PRINT"))
        self.lineSearch.setPlaceholderText(_translate("MainWindow", "Type the Employee\'s Name"))
        self.textData.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushModify.setText(_translate("MainWindow", "MODIFY"))
        self.comboList.setItemText(0, _translate("MainWindow", "ALL"))
        self.comboList.setItemText(1, _translate("MainWindow", "TEACHING PERSONNEL"))
        self.comboList.setItemText(2, _translate("MainWindow", "NON-TEACHING PERSONNEL"))
        self.comboList.setItemText(3, _translate("MainWindow", "PART TIME"))
        self.comboList.setItemText(4, _translate("MainWindow", "CONTRACT OF SERVICE"))
        self.comboList.setItemText(5, _translate("MainWindow", "SEPARATED"))
        __sortingEnabled = self.listE.isSortingEnabled()
        self.listE.setSortingEnabled(False)
        item = self.listE.item(0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listE.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listE.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listE.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listE.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listE.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listE.item(6)
        item.setText(_translate("MainWindow", "dsfsdfsdfsfsdfdsf"))
        self.listE.setSortingEnabled(__sortingEnabled)
        self.label_31.setText(_translate("MainWindow", "Employee Type:"))
        self.pushPrint_2.setText(_translate("MainWindow", "PRINT LIST OF PERSONELS"))
        self.label_33.setText(_translate("MainWindow", "Filter Search:"))
        self.label_12.setText(_translate("MainWindow", "*click the employee\'s name to view"))
        self.pushButton_9.setText(_translate("MainWindow", "Change Account\'s Verification Code"))
        self.pushButton_8.setText(_translate("MainWindow", "Change Account\'s Password"))
        self.pushButton.setText(_translate("MainWindow", "Change Account Username"))
        self.pushButton_10.setText(_translate("MainWindow", "Account Information"))
        self.label_78.setText(_translate("MainWindow", "New Username:"))
        self.label_79.setText(_translate("MainWindow", "Date Registered"))
        self.label_81.setText(_translate("MainWindow", "New Username:"))
        self.label_82.setText(_translate("MainWindow", "Confirm Validation Code:"))
        self.label_83.setText(_translate("MainWindow", "Confirm Password:"))
        self.confirmuser.setText(_translate("MainWindow", "Confirm"))
        self.label_84.setText(_translate("MainWindow", "Current Password:"))
        self.label_85.setText(_translate("MainWindow", "NewPassword:"))
        self.label_86.setText(_translate("MainWindow", "Confirm Password:"))
        self.confirmpass.setText(_translate("MainWindow", "Confirm"))
        self.label_90.setText(_translate("MainWindow", "Current Verification Code:"))
        self.label_91.setText(_translate("MainWindow", "New Verification Code:"))
        self.label_92.setText(_translate("MainWindow", "Confirm Verification Code:"))
        self.confirmpass_3.setText(_translate("MainWindow", "Confirm"))
        self.label_75.setText(_translate("MainWindow", "Account Settings"))
        self.label_32.setText(_translate("MainWindow", "Notification Sheet:"))
        self.pushupdatenotif.setText(_translate("MainWindow", "UPDATE"))
        self.textviewnotif.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Black\'; font-size:12pt;\">Dear </span><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600; color:#0055ff;\">**officer name </span><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600; color:#000000;\">:</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600;\">    We would like to inform you that our system  detected an employee to be promote on </span><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600; color:#0055ff;\">DATE</span><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600;\">.Please click the update button to update the date of last promotion of the employee. </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial Black\'; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600; color:#0055ff;\">Employee Information:</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial Black\'; font-size:12pt; font-weight:600;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600;\">Lastname: </span><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600; color:#0055ff;\">RILAN</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600;\">Firstname: </span><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600; color:#0055ff;\">MICHAEL ANGELO</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600;\">Middlename: </span><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600; color:#0055ff;\">SUAREZ</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600;\">Date of Last Promotion(yyyy-mm-dd): </span><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600; color:#0055ff;\">2017-11-7</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600;\">Date of Next Promotion(yyyy-mm-dd): </span><span style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:600; color:#0055ff;\">2020-11-7(3 days from now)</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "**Click the Notification Message to view"))
        self.label_3.setText(_translate("MainWindow", "Developed by: "))
        self.label_5.setText(_translate("MainWindow", "Rilan, Michael Angelo S."))
        self.label_6.setText(_translate("MainWindow", "Naz,Romwell M."))
        self.label_10.setText(_translate("MainWindow", "BET-CpET Non-STEM-2D Project SY.2020-2021"))
        self.commandLinkButton_4.setText(_translate("MainWindow", "Home"))
        self.commandLinkButton.setText(_translate("MainWindow", "ADD EMPLOYEE"))
        self.pushACC.setText(_translate("MainWindow", "ACCOUNT SETTING"))
        self.pushACC_2.setText(_translate("MainWindow", "NOTIFICATION"))
        self.label_53.setText(_translate("MainWindow", "First name*:"))
        self.label_54.setText(_translate("MainWindow", "Middle name:"))
        self.label_55.setText(_translate("MainWindow", "Last name*:"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Gender*"))
        self.radioMale_3.setText(_translate("MainWindow", "Male"))
        self.radioFemale_3.setText(_translate("MainWindow", "Female"))
        self.label_57.setText(_translate("MainWindow", "Designation*:"))
        self.label_58.setText(_translate("MainWindow", "Salary Grade*:"))
        self.label_59.setText(_translate("MainWindow", "Step Increment*:"))
        self.label_60.setText(_translate("MainWindow", "Date of Last Promotion*:"))
        self.label_61.setText(_translate("MainWindow", "Employment Status*:"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "....."))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "TEACHING PERSONNEL"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "NON-TEACHING PERSONNEL"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "PART TIME"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "CONTRACT OF SERVICE"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "SEPARATED"))
        self.lineFirstname_3.setPlaceholderText(_translate("MainWindow", "Firstname(i.e. RICARDO)"))
        self.lineMid_3.setPlaceholderText(_translate("MainWindow", "leave blank if No Middle name"))
        self.lineLastname_3.setPlaceholderText(_translate("MainWindow", "Last name (i.e. DALISAY)"))
        self.lineDesignation_3.setPlaceholderText(_translate("MainWindow", "Designation(letters only)"))
        self.lineSalaryg_3.setPlaceholderText(_translate("MainWindow", "Salary Grade(numbers only)"))
        self.lineStepincre_3.setPlaceholderText(_translate("MainWindow", "Step Increment(numbers only)"))
        self.label_66.setText(_translate("MainWindow", "PHILHEALTH*:"))
        self.lineTin_3.setPlaceholderText(_translate("MainWindow", "Enter 9 digits only"))
        self.label_63.setText(_translate("MainWindow", "GSIS*:"))
        self.label_65.setText(_translate("MainWindow", "PAGIBIG*:"))
        self.label_64.setText(_translate("MainWindow", "SSS*:"))
        self.linePhil_3.setPlaceholderText(_translate("MainWindow", "Enter 12 digits only"))
        self.label_67.setText(_translate("MainWindow", "Employee\'s Benefit Informations"))
        self.label_62.setText(_translate("MainWindow", "TIN*:"))
        self.linePagibig_3.setPlaceholderText(_translate("MainWindow", "Enter 12 digits only"))
        self.lineSss_3.setPlaceholderText(_translate("MainWindow", "Enter 10 digits only"))
        self.lineGsis_3.setPlaceholderText(_translate("MainWindow", "Enter 11 digits only"))
        self.label_68.setText(_translate("MainWindow", "Email*:"))
        self.lineEmail_3.setPlaceholderText(_translate("MainWindow", "email(i.e. abc123@....)"))
        self.label_69.setText(_translate("MainWindow", "Phone Number*:"))
        self.linePhone_7.setPlaceholderText(_translate("MainWindow", "phone number(i.e.09............)"))
        self.pushAdd.setText(_translate("MainWindow", "Save"))
        self.label_70.setText(_translate("MainWindow", "Employee\'s Personal Information"))
        self.label_71.setText(_translate("MainWindow", "ID NO*:"))
        self.linePhone_8.setPlaceholderText(_translate("MainWindow", "Employee ID(numbers only)"))
        self.linePhone_9.setPlaceholderText(_translate("MainWindow", "numbers only"))
        self.label_72.setText(_translate("MainWindow", "Item NO*:"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.pushbrowsepic.setText(_translate("MainWindow", "Browse "))
        self.label_73.setText(_translate("MainWindow", "First Day of Service*:"))
        self.dateEdit_2.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.label_77.setText(_translate("MainWindow", "Remarks:"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "type the remarks here"))
        self.label_2.setText(_translate("MainWindow", "note: all fields  that has  asterisk \'*\' should not leave empty"))
        self.label.setText(_translate("MainWindow", "            1X1 Picture*"))
        self.dateEdit_3.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.label_56.setText(_translate("MainWindow", "Birthday*:"))
import icons
import iconsnavigation


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
